[browser]
gatherUsageStats = false  # GDPR compliance

[theme]
primaryColor = "#E3000F"  # SPD red, or choose another color
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 